### Register
POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "test1@test.com",
    "password": "test",
    "username": "test1"
}

### login
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "test1@test.com",
    "password": "test"
}